name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler:
          - gcc-11
          - gcc-10
          - clang-12
          - clang-11
          - clang-10
    container:
      image: "registry.gitlab.com/offa/docker-images-ci/dist-stm32/${{ matrix.compiler }}:latest"
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: script/ci_build.sh -asan -ubsan

  build_arm:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler:
          - arm-none-eabi-gcc-10
        build_config:
          - {build_type: Debug, lto: OFF}
          - {build_type: Release, lto: OFF}
          - {build_type: MinSizeRel, lto: OFF}
          - {build_type: MinSizeRel, lto: ON}
    container:
      image: "registry.gitlab.com/offa/docker-images-ci/dist-stm32/${{ matrix.compiler }}:latest"
    name: "${{ matrix.compiler }} - ${{ matrix.build_config.build_type }} (LTO: ${{ matrix.build_config.lto }})"
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          export BUILD_TYPE=${{ matrix.build_config.build_type }}
          export LTO_ENABLED=${{ matrix.build_config.lto }}
          export COMPILER=${{ matrix.compiler }}
          script/ci_build.sh
